---
name: Build & Publish
run-name: Build Podman image and publish on the Container registry
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '@daily'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Container Registry URL
        id: set-registry-url
        run: |
          echo "registry-url=$(echo $GITHUB_SERVER_URL | sed 's#https\?://##')" >> $GITHUB_OUTPUT
          echo "repository-id=$(echo ${GITHUB_REPOSITORY,,})" >> $GITHUB_OUTPUT
        shell: bash
      - name: Check out code
        uses: actions/checkout@v4
      - name: Prepare BuildX
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
              [registry."${{ steps.set-registry-url.outputs.registry-url }}"]
              ca=["/etc/ssl/certs/ca-certificates.crt"]
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.set-registry-url.outputs.registry-url }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Ensure dependencies
        run: |
          apt-get update
          apt-get install podman -y
          pip install ansible-core ansible-builder ansible-navigator

      - name: Build image
        run: |
          ansible-builder build -v3 -t ${{ env.CONTAINER_TAG }}:latest
        env:
          CONTAINER_TAG: ${{ steps.set-registry-url.outputs.repository-id }}

      - name: Upload image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.CONTAINER_TAG }}
          tags: latest
          registry: ${{ steps.set-registry-url.outputs.registry-url }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        env:
          CONTAINER_TAG: ${{ steps.set-registry-url.outputs.repository-id }}
